import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

class PDFService {
  Future<void> generateSessionReport(Map<String, dynamic> sessionData) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text("SSEM - Study Environment Report", style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
              ),
              pw.SizedBox(height: 20),
              pw.Text("Session Summary", style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.Divider(),
              pw.Bullet(text: "Date: ${sessionData['date']}"),
              pw.Bullet(text: "Duration: ${sessionData['duration']}"),
              pw.Bullet(text: "Environment Score: ${sessionData['score']}/100"),
              pw.Bullet(text: "Alerts Count: ${sessionData['alerts']}"),
              pw.SizedBox(height: 20),
              pw.Text("Sensor Breakdown", style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.TableHelper.fromTextArray(
                context: context,
                data: <List<String>>[
                  <String>['Sensor', 'Value', 'Score Share'],
                  <String>['Noise', '${sessionData['noise']} dB', '${(sessionData['noise_score']).toStringAsFixed(1)}/100'],
                  <String>['Light', '${sessionData['light']} lux', '${(sessionData['light_score']).toStringAsFixed(1)}/100'],
                  <String>['Motion', '${sessionData['alerts']} events', '-${(sessionData['alerts'] * 5)} pts'],
                ],
              ),
              pw.SizedBox(height: 40),
              pw.Footer(
                trailing: pw.Text('Generated by SSEM App',
                    style: const pw.TextStyle(fontSize: 10)),
              ),
            ],
          );
        },
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File("${output.path}/ssem_report_${DateTime.now().millisecondsSinceEpoch}.pdf");
    await file.writeAsBytes(await pdf.save());
    
    await Share.shareXFiles([XFile(file.path)], text: 'SSEM Study Report (PDF)');
  }
}
