org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -Dsun.net.inetaddr.ttl=0 -Dnetworkaddress.cache.ttl=0 -Dnetworkaddress.cache.negative.ttl=0
android.useAndroidX=true
org.gradle.daemon=false
# Fix for camera_android_camerax MD5 hash bug with Gradle 8+
android.experimental.buildOnlyTargetAbi=false
